"""Execute every `*.ipynb` in this directory against the live EE backend.

Reads `GEE_SERVICE_ACCOUNT` and `GEE_SERVICE_KEY` from the environment;
each notebook picks them up via `os.environ[...]` at its first cell.
Re-writes the executed notebook in-place so outputs are committed.

Usage:
    GEE_SERVICE_ACCOUNT=...  GEE_SERVICE_KEY=...  python _execute.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import nbformat
from nbclient import NotebookClient
from nbclient.exceptions import CellExecutionError

HERE = Path(__file__).parent


def execute(path: Path, timeout: int = 240) -> bool:
    """Run notebook `path` in-place; return `True` on success."""
    print(f"\n>>> {path.name}", flush=True)
    nb = nbformat.read(path, as_version=4)
    client = NotebookClient(
        nb,
        timeout=timeout,
        kernel_name="python3",
        resources={"metadata": {"path": str(path.parent)}},
        allow_errors=False,
    )
    try:
        client.execute()
    except CellExecutionError as exc:
        print(f"    FAILED: {exc.ename}: {exc.evalue}", flush=True)
        nbformat.write(nb, path)
        return False
    nbformat.write(nb, path)
    print("    OK", flush=True)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "notebook", nargs="*",
        help="Notebook stems to run (default: every *.ipynb in this dir).",
    )
    parser.add_argument("--timeout", type=int, default=240)
    args = parser.parse_args()

    if args.notebook:
        files = [HERE / f"{n}.ipynb" if not n.endswith(".ipynb") else HERE / n for n in args.notebook]
    else:
        files = sorted(HERE.glob("*.ipynb"))
        # Skip the cached preview generated by jupyter (if any).
        files = [f for f in files if not f.name.startswith(".")]

    failures: list[str] = []
    for f in files:
        if not execute(f, timeout=args.timeout):
            failures.append(f.name)

    print(f"\n{len(files) - len(failures)} / {len(files)} notebooks executed cleanly")
    if failures:
        print("FAILED:", ", ".join(failures))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
