"""One-off migration: map free-text `provider:` strings to canonical slugs (M1).

Walks every ``catalog/*.yaml`` (except ``_index.yaml``), takes the current
``provider:`` value (~222 distinct strings as of 2026-05-16) and rewrites
each stanza to use one of ~70 canonical slug-ids defined in
``src/earthlens/gee/providers.yaml`` (also (re)generated by this script).

Strategy:

1. Try an exact match against ``_OVERRIDES`` first (covers tricky strings
   where keyword rules would mis-fire — joint productions, ambiguous
   abbreviations).
2. Fall back to substring/regex rules in ``_RULES`` (first-match-wins).
3. Anything left over is printed to stderr; we refuse to rewrite until
   every string is covered (the live catalog has 222 strings — coverage
   should be 100 %).

The script is idempotent: a value that's already a known slug (e.g.
``nasa-lp-daac``) is left in place.

Not part of the installed package — bulk-curation helper only.
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

CATALOG_DIR = Path("src/earthlens/gee/catalog")
PROVIDERS_PATH = Path("src/earthlens/gee/providers.yaml")


# ---------------------------------------------------------------------------
# Canonical registry — slug → (display_name, parent_slug_or_None)
# ---------------------------------------------------------------------------

# Order matters for output stability; alphabetical within sections.
REGISTRY: list[tuple[str, str, str | None]] = [
    # --- USA federal: NASA ---
    ("nasa", "NASA", None),
    ("nasa-asdc", "NASA ASDC", "nasa"),
    ("nasa-ges-disc", "NASA GES DISC", "nasa"),
    ("nasa-gmao", "NASA GMAO", "nasa"),
    ("nasa-gsfc", "NASA Goddard Space Flight Center", "nasa"),
    ("nasa-jpl", "NASA Jet Propulsion Laboratory", "nasa"),
    ("nasa-laads-daac", "NASA LAADS DAAC", "nasa"),
    ("nasa-lance", "NASA LANCE", "nasa"),
    ("nasa-lp-daac", "NASA Land Processes DAAC", "nasa"),
    ("nasa-nsidc-daac", "NASA NSIDC DAAC", "nasa"),
    ("nasa-ob-daac", "NASA OB.DAAC", "nasa"),
    ("nasa-ornl-daac", "NASA ORNL DAAC", "nasa"),
    ("nasa-sedac", "NASA SEDAC (CIESIN)", "nasa"),
    # --- USA federal: USDA ---
    ("usda", "USDA", None),
    ("usda-ars", "USDA ARS", "usda"),
    ("usda-fsa", "USDA FSA", "usda"),
    ("usda-nass", "USDA National Agricultural Statistics Service", "usda"),
    ("usda-usfs", "USDA Forest Service", "usda"),
    ("usda-usfs-gtac", "USDA Forest Service GTAC", "usda-usfs"),
    # --- USA federal: USGS, DOI, BLM, EPA, NSF, NOAA ---
    ("usgs", "USGS", None),
    ("usgs-google", "USGS / Google (Landsat publication)", "usgs"),
    ("blm", "US Bureau of Land Management", None),
    ("us-census-bureau", "US Census Bureau", None),
    ("us-epa", "US Environmental Protection Agency", None),
    ("us-state-dept", "US Department of State (Office of the Geographer)", None),
    ("noaa", "NOAA", None),
    ("noaa-nhc", "NOAA National Hurricane Center", "noaa"),
    ("noaa-psl", "NOAA Physical Sciences Laboratory", "noaa"),
    ("nopp", "US Naval Oceanographic Partnership Program (NOPP)", None),
    ("hycom-consortium", "HYCOM Consortium", None),
    # --- Europe ---
    ("copernicus", "Copernicus", None),
    ("copernicus-marine", "Copernicus Marine Service", "copernicus"),
    ("ecmwf", "ECMWF", None),
    ("esa", "European Space Agency", None),
    ("ec-jrc", "EC Joint Research Centre", None),
    ("eea", "European Environment Agency", None),
    ("vito", "VITO", None),
    ("cnes", "CNES", None),
    ("dlr", "DLR — German Aerospace Centre", None),
    ("ign", "IGN — French National Geographic Institute", None),
    ("uk-env-agency", "UK Environment Agency", None),
    ("ahn", "AHN — Actueel Hoogtebestand Nederland", None),
    ("swisstopo", "swisstopo", None),
    ("beeldmateriaal-nl", "Beeldmateriaal Nederland", None),
    ("national-orthophotos", "European national orthophoto programmes", None),
    # --- UN family ---
    ("fao", "FAO UN", None),
    ("unep-wcmc", "UNEP-WCMC / Protected Planet", None),
    ("un-geodata", "United Nations Geospatial", None),
    ("iucn", "IUCN", None),
    ("ipcc", "IPCC", None),
    ("iahs", "IAHS", None),
    # --- JAXA ---
    ("jaxa", "JAXA", None),
    # --- Other national agencies ---
    ("aafc", "Agriculture and Agri-Food Canada", None),
    ("nrcan", "Natural Resources Canada", None),
    ("nfis-canada", "National Forest Information System (Canada)", None),
    ("cec", "Commission for Environmental Cooperation", None),
    ("geoscience-australia", "Geoscience Australia", None),
    ("tern-csiro", "TERN Landscapes / CSIRO Land and Water", None),
    ("csiro", "CSIRO", None),
    ("bnetd-cign", "BNETD-CIGN (Côte d'Ivoire)", None),
    # --- Research universities / labs ---
    ("boston-university", "Boston University", None),
    ("bnu", "Beijing Normal University", None),
    ("bochum-urban-climate", "Bochum Urban Climate Lab", None),
    ("cas-igsnrr", "CAS IGSNRR", None),
    ("cpom", "Centre for Polar Observation and Modelling", None),
    ("csic", "CSIC", None),
    ("csm-payne-institute", "Colorado School of Mines (Payne Institute)", None),
    ("humboldt-berlin", "Humboldt University of Berlin", None),
    ("k-n-toosi-uni", "K. N. Toosi University of Technology", None),
    ("larse-usfs", "USFS Laboratory for Applications of Remote Sensing in Ecology (LARSE)", "usda-usfs"),
    ("montana-ntsg", "University of Montana NTSG", None),
    ("montana-climate-office", "Montana Climate Office", None),
    ("neon", "National Ecological Observatory Network (NEON)", None),
    ("oxford-malaria-atlas", "Oxford Malaria Atlas Project", None),
    ("oregonstate-prism", "PRISM Climate Group, Oregon State University", None),
    ("pku-rel", "Peking University Remote Sensing Lab (PKU REL)", None),
    ("snu", "Seoul National University", None),
    ("tsinghua", "Tsinghua University", None),
    ("tu-berlin", "TU Berlin", None),
    ("uc-berkeley-worldclim", "WorldClim — UC Berkeley", None),
    ("uc-merced", "University of California Merced", None),
    ("umd-glad", "UMD GLAD", None),
    ("umn-pgc", "University of Minnesota Polar Geospatial Center", None),
    ("uni-tokyo", "University of Tokyo", None),
    ("uq-murray", "University of Queensland (Murray group)", None),
    ("jcu-murray", "James Cook University (Murray group)", None),
    ("wm-geolab", "William and Mary geoLab (geoBoundaries)", None),
    ("whrc", "Woods Hole Research Center", None),
    ("yceo-yale", "Yale Center for Earth Observation (YCEO)", None),
    # --- Earth Observation, data publishers, commercial, NGO ---
    ("aca", "Allen Coral Atlas Partnership", None),
    ("biopama", "BIOPAMA programme", None),
    ("c2s-dfo", "Cloud to Street / Dartmouth Flood Observatory", None),
    ("ciesin", "CIESIN", None),
    ("earth-big-data", "Earth Big Data LLC", None),
    ("edf-methanesat", "Environmental Defense Fund — MethaneSAT", None),
    ("envirometrix-openlandmap", "EnvirometriX (OpenLandMap)", None),
    ("forest-data-partnership", "Forest Data Partnership", None),
    ("global-fishing-watch", "Global Fishing Watch", None),
    ("global-pasture-watch", "Global Pasture Watch", None),
    ("google", "Google", None),
    ("google-research", "Google Research", "google"),
    ("google-cloud-publicdata", "Google Cloud Public Data", "google"),
    ("gfw", "Global Forest Watch (WRI)", None),
    ("hansen-umd-google", "Hansen / UMD / Google / USGS / NASA (forest change)", None),
    ("inaturalist", "iNaturalist", None),
    ("isda", "iSDA", None),
    ("isric", "ISRIC — World Soil Information", None),
    ("kbas", "Key Biodiversity Areas (KBAs)", None),
    ("mapbiomas", "MapBiomas", None),
    ("mtbs", "Monitoring Trends in Burn Severity (MTBS)", None),
    ("nature-trace", "Nature Trace", None),
    ("ndmc", "US National Drought Mitigation Center", None),
    ("openet", "OpenET, Inc.", None),
    ("ornl", "Oak Ridge National Laboratory", None),
    ("overture-maps", "Overture Maps Foundation", None),
    ("planet", "Planet Labs", None),
    ("pml-v2", "PML_V2 team", None),
    ("resolve", "RESOLVE Biodiversity and Wildlife Solutions", None),
    ("sat-io", "Sat-IO open-datasets republication", None),
    ("ucsb-chc", "UCSB Climate Hazards Center", None),
    ("worldpop", "WorldPop", None),
    ("wri", "World Resources Institute", None),
    ("wwf", "WWF", None),
    ("ee-publisher", "Earth Engine catalog publisher (unspecified)", None),
]

_KNOWN_SLUGS: set[str] = {slug for slug, _, _ in REGISTRY}


# ---------------------------------------------------------------------------
# Explicit string → slug overrides (try these first; bypass the rule table)
# ---------------------------------------------------------------------------

_OVERRIDES: dict[str, str] = {
    # Tricky / joint productions where rules would mis-route.
    "Hansen / UMD / Google / USGS / NASA": "hansen-umd-google",
    "Hansen/UMD/Google/USGS/NASA": "hansen-umd-google",
    "Murray/UQ/Google/USGS/NASA": "uq-murray",
    "Murray/JCU": "jcu-murray",
    "QA Filtered: Google and NASA ASDC": "nasa-asdc",
    "NASA / USFS LARSE / Google": "larse-usfs",
    "NASA / USFS LARSE": "larse-usfs",
    "Indexing: Google and USFS Laboratory for Applications of Remote Sensing in Ecology": "larse-usfs",
    "Rasterization: Google and USFS Laboratory for Applications of Remote Sensing in Ecology": "larse-usfs",
    "USFS Laboratory for Applications of Remote Sensing in Ecology (LARSE)": "larse-usfs",
    "NDMC / USDA / NOAA (republished via sat-io)": "ndmc",
    "Oak Ridge National Laboratory (republished via sat-io)": "ornl",
    "GLOBathy / Sat-IO open-datasets": "sat-io",
    "Earth Observation Group, Payne Institute for Public Policy, Colorado School of Mines": "csm-payne-institute",
    "Earth Observation Group, Colorado School of Mines": "csm-payne-institute",
    "NOAA / Earth Observation Group, Colorado School of Mines": "csm-payne-institute",
    "Numerical Terradynamic Simulation Group, The University of Montana": "montana-ntsg",
    "University of Montana / Montana Climate Office": "montana-climate-office",
    "University of Montana Numerical Terradynamic Simulation Group (NTSG)": "montana-ntsg",
    "Baccini, A. (Woods Hole Research Center), Sulla-Menashe, D. (Boston University)": "boston-university",
    "Geoscience Australia / DEA (NGIS catalogue)": "geoscience-australia",
    "Geography Department, Humboldt University of Berlin, Berlin, Germany": "humboldt-berlin",
    "Institute of Industrial Science, The University of Tokyo, Japan": "uni-tokyo",
    "Dai Yamazaki — University of Tokyo": "uni-tokyo",
    "Dai Yamazaki (University of Tokyo)": "uni-tokyo",
    "Department of Earth System Science, Tsinghua University (DESS, THU)": "tsinghua",
    "Bochum Urban Climate Lab": "bochum-urban-climate",
    "NRCan": "nrcan",
    "IGN": "ign",
    "ESA / Copernicus / Sentinel Hub": "esa",
    "ESA WorldCover Consortium": "esa",
    "ESA WorldCereal Consortium": "esa",
    "ESA Biomass CCI": "esa",
    "ESA Climate Change Initiative — Fire ECV": "esa",
    "ESA": "esa",
    "Copernicus / VITO": "vito",
    "Copernicus": "copernicus",
    "ESA / Copernicus": "copernicus",
    "EEA / Copernicus": "eea",
    "European Union / ESA / Copernicus": "copernicus",
    "European Union/ESA/Copernicus": "copernicus",
    "Vito / ESA": "vito",
    "Google/CNES": "cnes",
    "Google Earth Engine": "google",
    "Google": "google",
    "Google Research - Open Buildings": "google-research",
    "Google / Aclima": "google",
    "Google WeatherNext / GCP Public Data": "google-cloud-publicdata",
    "Google Global Precipitation Nowcast": "google-cloud-publicdata",
    "Planet Labs Inc.": "planet",
    "Planet Labs (NICFI programme)": "planet",
    "USGS / Google": "usgs-google",
    "USGS/Google": "usgs-google",
    "EC JRC / Google": "ec-jrc",
    "EC JRC": "ec-jrc",
    "Joint Research Centre, European Commission": "ec-jrc",
    "Joint Research Center, Unit D5": "ec-jrc",
    "European Commission, Joint Research Centre, Global Wildfire Information System": "ec-jrc",
    "Allen Coral Atlas Partnership (ACA)": "aca",
    "Allen Coral Atlas Partnership": "aca",
    "USGS / NASA MEaSUREs": "usgs",
    "USGS / Bureau of Land Management": "usgs",
    "United States Geological Survey and Bureau of Land Management": "usgs",
    "USGS": "usgs",
    "United States Geological Survey": "usgs",
    "US Geological Survey": "usgs",
    "United States Department of State, Office of the Geographer": "us-state-dept",
    "United States Census Bureau": "us-census-bureau",
    "United States Environmental Protection Agency": "us-epa",
    "USDA-ARS": "usda-ars",
    "USDA FSA": "usda-fsa",
    "USDA National Agricultural Statistics Service": "usda-nass",
    "USDA Forest Service / DOI": "usda-usfs",
    "USDA Forest Service GTAC": "usda-usfs-gtac",
    "USDA Forest Service Research Data Archive": "usda-usfs",
    "USDA Forest Service (USFS) Geospatial Technology and Applications Center (GTAC)": "usda-usfs-gtac",
    "USDA Forest Service (USFS) Field Services and Innovation Center Geospatial Office": "usda-usfs",
    "U.S. Department of Agriculture's (USDA), U.S. Forest Service (USFS), U.S.": "usda-usfs",
    "Monitoring Trends in Burn Severity (MTBS)": "mtbs",
    "Commission for Environmental Cooperation (CEC)": "cec",
    "Bureau of Land Management": "blm",
    "US Department of Interior Bureau of Land Management (BLM)": "blm",
    "Centre for Polar Observation and Modelling (CPOM)": "cpom",
    "International Union for Conservation of Nature and Natural Resources": "iucn",
    "UN Environment World Conservation Monitoring Centre (UNEP-WCMC) / Protected Planet": "unep-wcmc",
    "UNEP-WCMC": "unep-wcmc",
    "United Nations Geospatial": "un-geodata",
    "World Resources Institute": "wri",
    "World Resources Institute / Global Forest Watch": "gfw",
    "Global Forest Watch, World Resources Institute": "gfw",
    "WRI Land and Carbon": "wri",
    "WRI": "wri",
    "WWF": "wwf",
    "FAO UN": "fao",
    "FAO Forestry Division (FPP 1km)": "fao",
    "FAO Forestry Division (TPP 500m cropland)": "fao",
    "iSDA": "isda",
    "ISRIC — World Soil Information": "isric",
    "CIESIN": "ciesin",
    "NASA SEDAC / CIESIN": "nasa-sedac",
    "NASA SEDAC at the Center for International Earth Science Information Network": "nasa-sedac",
    "NASA NSIDC DAAC at CIRES": "nasa-nsidc-daac",
    "NSIDC": "nasa-nsidc-daac",
    "National Snow and Ice Data Center (NSDIC)": "nasa-nsidc-daac",
    "NASA NSIDC DAAC": "nasa-nsidc-daac",
    "NASA / NOAA": "nasa",
    "NASA / Climate Analytics Group": "nasa",
    "NASA /  Climate Analytics Group": "nasa",
    "NASA / GES DISC": "nasa-ges-disc",
    "NASA / CGIAR-CSI": "nasa",
    "NASA / USGS / JPL-Caltech": "nasa-jpl",
    "NASA/USGS/JPL-Caltech": "nasa-jpl",
    "NASA/MERRA": "nasa-gmao",
    "NASA / GMAO": "nasa-gmao",
    "NASA / LANCE / NOAA20_VIIRS": "nasa-lance",
    "NASA / LANCE / SNPP_VIIRS": "nasa-lance",
    "NASA / LANCE / EOSDIS": "nasa-lance",
    "NASA GSFC": "nasa-gsfc",
    "NASA GES DISC": "nasa-ges-disc",
    "NASA GES DISC at Goddard Space Flight Center": "nasa-ges-disc",
    "NASA GES DISC at NASA Goddard Space Flight Center": "nasa-ges-disc",
    "NASA JPL": "nasa-jpl",
    "NASA/JPL": "nasa-jpl",
    "NASA Jet Propulsion Laboratory": "nasa-jpl",
    "NASA ASDC": "nasa-asdc",
    "NASA LAADS DAAC": "nasa-laads-daac",
    "NASA LAADS DAAC at NASA Goddard Space Flight Center": "nasa-laads-daac",
    "NASA Land SIPS": "nasa",
    "NASA ORNL DAAC": "nasa-ornl-daac",
    "NASA ORNL DAAC at Oak Ridge National Laboratory": "nasa-ornl-daac",
    "NASA OB.DAAC": "nasa-ob-daac",
    "NASA OB.DAAC at NASA Goddard Space Flight Center": "nasa-ob-daac",
    "Land Processes Distributed Active Archive Center": "nasa-lp-daac",
    "NASA LP DAAC": "nasa-lp-daac",
    "NASA LP DAAC at the USGS EROS Center": "nasa-lp-daac",
    "ECMWF": "ecmwf",
    "ECMWF / Copernicus C3S": "ecmwf",
    "ECMWF / Copernicus Climate Change Service (C3S)": "ecmwf",
    "Copernicus Marine Service": "copernicus-marine",
    "Copernicus Marine Service Global Ocean Waves and Forecasts": "copernicus-marine",
    "NOAA": "noaa",
    "NOAA NHC": "noaa-nhc",
    "NOAA Physical Sciences Laboratory": "noaa-psl",
    "NOAA / NCEP": "noaa",
    "NOAA / NCEP / NCAR": "noaa",
    "NOAA / NCEP / EMC": "noaa",
    "NOAA NCEP-DOE": "noaa",
    "NOAA NWS National Centers for Environmental Prediction (NCEP)": "noaa",
    "NOAA NWS": "noaa",
    "NOAA CDR Program": "noaa",
    "NOAA NGDC": "noaa",
    "NOAA NCEI": "noaa",
    "NOAA NCDC": "noaa",
    "HYCOM Consortium / NOPP": "hycom-consortium",
    "NOPP": "nopp",
    "PML_V2": "pml-v2",
    "PML_V2 Evapotranspiration team": "pml-v2",
    "CAS IGSNRR / PML_V2 team": "cas-igsnrr",
    "Numerical Terradynamic Simulation Group, The University of Montana": "montana-ntsg",
    "Oxford Malaria Atlas Project": "oxford-malaria-atlas",
    "OpenET, Inc.": "openet",
    "Forest Data Partnership": "forest-data-partnership",
    "Global Pasture Watch": "global-pasture-watch",
    "Global Fishing Watch": "global-fishing-watch",
    "Environmental Defense Fund - MethaneSAT": "edf-methanesat",
    "Environmental Defense Fund (EDF) — MethaneSAT": "edf-methanesat",
    "Key Biodiversity Areas (KBAs) republication": "kbas",
    "Lemur Forest Inventory (gcpm041u)": "ee-publisher",
    "Conservation Science Partners": "ee-publisher",
    "Nature Trace": "nature-trace",
    "MapBiomas": "mapbiomas",
    "AHN": "ahn",
    "Topography swisstopo": "swisstopo",
    "Beeldmateriaal Nederland": "beeldmateriaal-nl",
    "Estonia orthophotos": "national-orthophotos",
    "Latvia orthophotos": "national-orthophotos",
    "Spain orthophotos": "national-orthophotos",
    "Brandenburg orthophotos": "national-orthophotos",
    "Slovakia orthophotomosaic": "national-orthophotos",
    "NLS orthophotos": "national-orthophotos",
    "TUBerlin / BigEarthNet": "tu-berlin",
    "Peking University Remote Sensing Lab (PKU REL)": "pku-rel",
    "Seoul National University (SNU)": "snu",
    "Tsinghua University": "tsinghua",
    "JAXA Earth Observation Research Center": "jaxa",
    "JAXA EORC": "jaxa",
    "JAXA GCOM Project": "jaxa",
    "EnvirometriX Ltd": "envirometrix-openlandmap",
    "EnvirometriX / OpenLandMap": "envirometrix-openlandmap",
    "WorldPop": "worldpop",
    "WorldClim — University of California, Berkeley": "uc-berkeley-worldclim",
    "PRISM Climate Group, Oregon State University": "oregonstate-prism",
    "PRISM / OREGONSTATE": "oregonstate-prism",
    "UCSB / CHG": "ucsb-chc",
    "UCSB / CHC": "ucsb-chc",
    "UCSB": "ucsb-chc",
    "University of Minnesota Polar Geospatial Center": "umn-pgc",
    "University of California Merced": "uc-merced",
    "Yale Center for Earth Observation (YCEO)": "yceo-yale",
    "UK Environment Agency": "uk-env-agency",
    "DLR — German Aerospace Centre": "dlr",
    "German Aerospace Centre (DLR)": "dlr",
    "RESOLVE Biodiversity and Wildlife Solutions": "resolve",
    "TERN Landscapes / CSIRO Land and Water": "tern-csiro",
    "CSIRO / SLGA": "csiro",
    "CSIC": "csic",
    "Cloud to Street (C2S) / Dartmouth Flood Observatory (DFO)": "c2s-dfo",
    "UMD GLAD": "umd-glad",
    "Global Food Security-support Analysis Data at 30m Project (GFSAD30)": "usgs",
    "Oak Ridge National Laboratory": "ornl",
    "Earth Observation Group, Payne Institute for Public Policy, Colorado School of Mines": "csm-payne-institute",
    "Earth Observation Group, Colorado School of Mines": "csm-payne-institute",
    "Earth Big Data LLC": "earth-big-data",
    "BIOPAMA programme": "biopama",
    "BNETD-CIGN": "bnetd-cign",
    "Beijing Normal University": "bnu",
    "National Forest Information System (Canada)": "nfis-canada",
    "Agriculture and Agri-Food Canada": "aafc",
    "K. N. Toosi University of Technology LiDAR Lab": "k-n-toosi-uni",
    "iNaturalist": "inaturalist",
    "Overture Maps Foundation": "overture-maps",
    "Geoscience Australia": "geoscience-australia",
    "National Ecological Observatory Network (NEON)": "neon",
    "IPCC": "ipcc",
    "IAHS": "iahs",
    "William and Mary geoLab": "wm-geolab",
    "Woods Hole Research Center": "whrc",
    "GeoBoundaries / William and Mary geoLab": "wm-geolab",
}


# ---------------------------------------------------------------------------
# Fallback regex rules (last resort; warn if hit, since overrides should cover)
# ---------------------------------------------------------------------------

_RULES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^Earth Engine catalog publisher", re.I), "ee-publisher"),
]


def slug_for(text: str) -> str | None:
    """Return the canonical slug for `text`, or `None` if unrecognised.

    `text` may already be a known slug — that path returns it unchanged
    (so the script is idempotent).
    """
    if text in _KNOWN_SLUGS:
        return text
    if text in _OVERRIDES:
        return _OVERRIDES[text]
    for pattern, slug in _RULES:
        if pattern.search(text):
            return slug
    return None


def _write_providers_yaml() -> None:
    lines = [
        "# Canonical providers for the GEE catalog (M1).\n",
        "# Each entry maps a stable slug-id to a display name and optional\n",
        "# parent slug. Datasets in `catalog/*.yaml` reference providers by\n",
        "# slug via the `provider:` field; the loader validates that every\n",
        "# referenced slug is defined here.\n",
        "\n",
        "providers:\n",
    ]
    for slug, display, parent in REGISTRY:
        lines.append(f"  {slug}:\n")
        # double-quote the display so colons and parens don't need escaping
        display_yaml = display.replace('"', '\\"')
        lines.append(f'    display_name: "{display_yaml}"\n')
        if parent:
            lines.append(f"    parent: {parent}\n")
    PROVIDERS_PATH.write_text("".join(lines), encoding="utf-8")


_PROVIDER_LINE = re.compile(r"^(?P<lead>    provider:[ \t]*)(?P<value>.+?)[ \t]*$", re.MULTILINE)


def _unquote_yaml_scalar(raw: str) -> str:
    """Strip YAML single- or double-quoting from a scalar value."""
    if raw.startswith("'") and raw.endswith("'"):
        return raw[1:-1].replace("''", "'")
    if raw.startswith('"') and raw.endswith('"'):
        return raw[1:-1].replace('\\"', '"')
    return raw


def _rewrite_file(path: Path, mapping: dict[str, str]) -> tuple[int, int]:
    text = path.read_text(encoding="utf-8")
    replaced = 0
    unknown = 0

    # Walk every `    provider: <value>` line, rebuilding the file
    # text as we go. Avoids a `re.sub` closure (L1: no nested fns).
    parts: list[str] = []
    last_end = 0
    for match in _PROVIDER_LINE.finditer(text):
        parts.append(text[last_end:match.start()])
        value = _unquote_yaml_scalar(match.group("value"))
        slug = mapping.get(value)
        if slug is None:
            unknown += 1
            parts.append(match.group(0))
        elif value == slug:
            parts.append(match.group(0))
        else:
            replaced += 1
            parts.append(f"{match.group('lead')}{slug}")
        last_end = match.end()
    parts.append(text[last_end:])
    new_text = "".join(parts)
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")
    return replaced, unknown


def main() -> int:
    if not CATALOG_DIR.is_dir():
        print(f"catalog dir not found: {CATALOG_DIR}", file=sys.stderr)
        return 1

    # 1. Collect every distinct provider string from the live YAMLs.
    distinct: Counter[str] = Counter()
    files = sorted(p for p in CATALOG_DIR.glob("*.yaml") if p.name != "_index.yaml")
    for path in files:
        text = path.read_text(encoding="utf-8")
        for m in _PROVIDER_LINE.finditer(text):
            raw = m.group("value")
            if raw.startswith("'") and raw.endswith("'"):
                value = raw[1:-1].replace("''", "'")
            elif raw.startswith('"') and raw.endswith('"'):
                value = raw[1:-1].replace('\\"', '"')
            else:
                value = raw
            distinct[value] += 1

    # 2. Build the mapping; report any string we can't classify.
    mapping: dict[str, str] = {}
    unknown: list[str] = []
    for value in distinct:
        slug = slug_for(value)
        if slug is None:
            unknown.append(value)
        else:
            mapping[value] = slug

    if unknown:
        print(f"refusing to rewrite — {len(unknown)} unmapped provider strings:", file=sys.stderr)
        for value in sorted(unknown):
            print(f"  {distinct[value]:4d}  {value!r}", file=sys.stderr)
        return 1

    # 3. Emit providers.yaml.
    PROVIDERS_PATH.parent.mkdir(parents=True, exist_ok=True)
    _write_providers_yaml()
    print(f"wrote {PROVIDERS_PATH} ({len(REGISTRY)} canonical providers)")

    # 4. Rewrite every catalog file.
    total_replaced = 0
    for path in files:
        replaced, _ = _rewrite_file(path, mapping)
        if replaced:
            print(f"  {replaced:4d}  {path.name}")
        total_replaced += replaced
    print(
        f"rewrote {total_replaced} provider lines across {len(files)} files "
        f"({len(distinct)} distinct input strings -> {len(set(mapping.values()))} slugs)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
